image: java:8

stages:
  - build
  - deploy

build:
  stage: build
  script: ./mvnw package
  artifacts:
    paths:
      - target/greeter-0.0.1-SNAPSHOT.jar

production:
  stage: deploy
  script:
  - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
  - ./cf login -p $CF_PASSWORD -u $CF_USERNAME -a api.run.pivotal.io
  - ./cf target -o nipuna-cloud-demo -s development
  - ./cf push -p target/greeter-0.0.1-SNAPSHOT.jar
  only:
  - master

